apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulado-ingress
  namespace: jpncloud
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - labs.jpncloud.com.br
      secretName: labs-jpncloud-tls
  rules:
    - host: labs.jpncloud.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simulado-lb
                port:
                  number: 80