apiVersion: v1
kind: Service
metadata:
  name: simulado-service
  namespace: jpncloud
spec:
  selector:
    app: simulado
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8501 